name: Deploy on Merge

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' 

    - name: Install SF CLI
      uses: svierk/sfdx-cli-setup@main

    - name: Salesforce Org Login via SFDX Auth URL
      uses: svierk/sfdx-login@main
      with:
        sfdx-url: ${{ secrets.SFDX_AUTH_URL }}
        alias: my-org
          
    - name: Full Deploy to Production
      run: |
        sfdx project deploy start \
          --manifest package.xml \
          --target-org my-org \
          --wait 10 \
          --ignore-conflicts \
          --ignore-errors \
          --test-level NoTestRun

          
