name: Deploy on Merge

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' 

    - name: Install SF CLI
      uses: svierk/sfdx-cli-setup@main

    - name: Salesforce Org Login via SFDX Auth URL
      uses: svierk/sfdx-login@main
      with:
        sfdx-url: ${{ secrets.SFDX_AUTH_URL }}
        alias: my-org
          
    - name: Full deploy to production
      run: sfdx force:source:deploy -u ${{ secrets.SF_USERNAME }} -p force-app/main/default

    - name: Run Apex tests
      run: sfdx force:apex:test:run --targetusername ${{ secrets.SF_USERNAME }} --resultformat human
