name: Pull Request Validation

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install the npm and SFDX CLI
      run: |
          npm install
          npm install sfdx-cli --global
      
    - name: Authenticate with Salesforce
      run: sfdx auth:jwt:grant --clientid ${{ secrets.CLIENT_ID }} --jwtkeyfile assets/server.key --username ${{ secrets.SF_USERNAME }} --instanceurl https://login.salesforce.com

    - name: Validate Build
      run: sfdx force:source:deploy --checkonly --targetusername ${{ secrets.SF_USERNAME }} --wait 10
      continue-on-error: true

    - name: Run Apex Tests
      run: sfdx force:apex:test:run --targetusername ${{ secrets.SF_USERNAME }} --wait 10 --resultformat human
      continue-on-error: true
        
    - name: Set Build Flag on Failure
      if: failure()
      run: echo "Validation failed, setting flag"
